const { withGradleProperties } = require('expo/config-plugins');

// Dev-only convenience: this repo's native builds happen on a single machine
// against a single physical device (see memory.md "Contrainte de
// vérification (ce VPS)"), never a multi-arch release build. Building all 4
// ABIs (armeabi-v7a/arm64-v8a/x86/x86_64) compiles reanimated/gesture-handler/
// worklets' C++ four times over, which pushed a single `gradlew installDebug`
// past the 10-minute background-task ceiling of the tooling used to drive
// these builds. Restricting to arm64-v8a (the connected device's ABI) cut
// that build from >10 min (killed, never finished) to ~5 min. `android/` is
// regenerated by `expo prebuild` and never committed, so this has to be a
// config plugin, not a hand-edited file — same pattern as `withGradleJdk17.js`.
// MUST be removed (or made conditional) before ever producing a real
// multi-device/distribution build.
module.exports = function withDevSingleAbi(config) {
  return withGradleProperties(config, (config) => {
    const existing = config.modResults.find(
      (item) => item.type === 'property' && item.key === 'reactNativeArchitectures'
    );
    if (existing) {
      existing.value = 'arm64-v8a';
    } else {
      config.modResults.push({ type: 'property', key: 'reactNativeArchitectures', value: 'arm64-v8a' });
    }
    return config;
  });
};
