const { withGradleProperties, withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

// AGP's Prefab/CMake configure tasks can resolve a newer auto-provisioned
// Gradle toolchain (e.g. JDK 25) independently of Android Studio's own
// "Gradle JVM" setting, and JDK 22+ emits a JEP 451 "restricted method"
// warning that a Prefab bug (GeneratePrefabPackagesKt.reportErrors) treats
// as fatal. Pinning Gradle's toolchain resolution to the machine's own
// JAVA_HOME (set by installing a standalone JDK 17, e.g. Eclipse Temurin)
// avoids it. Reads JAVA_HOME at `expo prebuild` time so this stays portable
// across machines instead of hardcoding one developer's install path.
// `android/` is regenerated by `expo prebuild --clean` and never committed
// (see file-index.md), so this fix has to be re-applied as a config plugin,
// not as a hand-edited file.
module.exports = function withGradleJdk17(config) {
  const javaHome = process.env.JAVA_HOME;

  if (javaHome) {
    config = withGradleProperties(config, (config) => {
      const normalized = javaHome.replace(/\\/g, '/');
      config.modResults.push(
        { type: 'property', key: 'org.gradle.java.installations.paths', value: normalized },
        { type: 'property', key: 'org.gradle.java.installations.auto-download', value: 'false' },
        { type: 'property', key: 'org.gradle.java.installations.auto-detect', value: 'false' },
      );
      return config;
    });
  }

  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const filePath = path.join(config.modRequest.platformProjectRoot, 'gradle', 'gradle-daemon-jvm.properties');
      fs.mkdirSync(path.dirname(filePath), { recursive: true });
      fs.writeFileSync(filePath, 'toolchainVersion=17\n');
      return config;
    },
  ]);

  return config;
};
